### ISSUE TITLE
数据集格式信息问题

### ISSUE THREAD

**Issue by Balabala-Hong** [ViTAE-Transformer/SAMRS#15]
你好，想请教下您生成的SAMRS中数据集实例分割标注的格式是怎样的，以SIOR为例解析`ins`标注文件夹下的pkl文件得到如下信息：
![屏幕截图 2024-01-16 104509](https://github.com/ViTAE-Transformer/SAMRS/assets/38310647/9c01a504-8741-47e5-a72f-59867f06aaba)
我本身是想用实例分割的mask标注进行可视化，但是这里的mask标签是一串字符串，是我解析的方式有什么问题吗？

**Comment by DotWang** [comment]
@Balabala-Hong 这是COCO标准的RLE格式，可以转成二值图

**Comment by Balabala-Hong** [comment]
好的，非常感谢您的解答！
