### ISSUE TITLE
关于数据集尺寸的问题

### ISSUE THREAD

**Issue by Nyquist24** [ViTAE-Transformer/SAMRS#27]
请问作者，数据集的H, W必须相同吗，如果是高宽不一致的图像该如何得到对应( H, W )的mask

**Comment by DotWang** [comment]
@Nyquist24 这个应该取决于SAM的设置吧，不行就滑窗预测

**Comment by Nyquist24** [comment]
在你的提醒下我重新检查了，是因为我输入的图片的channel = 4导致的，谢谢。
