### ISSUE TITLE
visualize.py文件中不同颜色的mask像素值和类别名的对应关系

### ISSUE THREAD

**Issue by 1e12Leon** [ViTAE-Transformer/SAMRS#40]
作者您好，非常感谢你们的工作，请问37个类别和visualize.py文件中不同颜色的mask像素值的对应关系是mapping中的顺序吗？
例如 0: (0, 127, 255)对应FAIR1M中的第一个类别A220？

**Comment by DotWang** [comment]
@1e12Leon 是的

**Comment by 1e12Leon** [comment]
> @1e12Leon 是的
嗯嗯好的好的谢谢，是我犯了个小错误导致没匹配上，我以为不是这个对应关系，已经解决了，祝科研顺利！
